export const pagesData = [
  {
    id: 0,
    name: 'Astounding Lobby Areas',
    slug: 'astounding-lobby-area-designs',
    noItems: '2047',
    heading: 'Astounding Lobby Areas',
    desc: 'That a Walk to Remember, a beautiful Lobby Area is the first impression one has of entering your residence. We design your lobby areas to perfection and uniqueness as no 2 lobby areas of our projects are the same. We add creativity in all our projects, this gives us challenges and brings forth a new trend with every happy home delivered.',
    items: [],
  },
  {
    id: 1,
    name: 'Artistic Bedroom',
    slug: 'artistic-bedroom-designs',
    noItems: '2874',
    heading: 'Artistic Bedroom',
    desc: 'Now When you have reached us, keep the faith that we will Create some of the most artistic bedrooms for you, something inspiring, something trendy which delights you of a comforting personal space. Get in touch with our Expert who will guide you all throughout. Connect with us Today.',
    items: [],
  },
  {
    id: 2,
    name: 'Comfort Balcony Area',
    slug: 'comforting-balcony-area-designs',
    noItems: '1816',
    heading: 'Comfort Balcony Area',
    desc: 'The Most Important area in the residence is what we feel is the Balcony area, the more the better. A Balcony with a Good View is a luxury, enjoyed by a few. That is what we say, but now understanding the decorations of those areas, we have hundreds of designs. Connect with our team to get a nice balcony design for your residence. You will simply Love it.',
    items: [],
  },
  {
    id: 3,
    name: 'Soulful kids Room',
    slug: 'soulful-kids-room-designs',
    noItems: '162',
    heading: 'Soulful Kids Room',
    desc: 'We all want to make the kids room vibrant, flamboyant, playful and also a Happy place, where kids can enjoy different themes. Keeping in mind the colour creativity and the modular furniture required, we design your kids room to perfection. We create out of the box designs which are loved by parents as well as Kids. Connect with us Today to get a Playful Solution. ',
    items: [],
  },
  {
    id: 4,
    name: 'Relaxed Walk in Wardrobe',
    slug: 'relaxed-walk-in-wardrobe-designs',
    noItems: '809',
    heading: 'Relaxed Walk in Wardrobe',
    desc: 'We all need Well Fitted Wardrobes, just like our apparel. Anything out of order would spoil the entire purpose. At the Design Indian Homes, our In-house Brand Design Indian Wardrobe provides us the most perfect fitted Wardrobes, custom wardrobes. We specialise in Exclusive Walk-in Wardrobes which simply lightens up the room where the closet is fitted. We have mastery in manufacturing walk-in wardrobes since when there is space, there will be a cool walk-in to organize your apparel and enjoy. Connect without Team Today and Get the Most Affordable Walk-in Wardrobe.',
    items: [],
  },
  {
    id: 5,
    name: 'Handsome Modular Wardrobe',
    slug: 'handsome-modular-wardrobe-designs',
    noItems: '1165',
    heading: 'Handsome Modular Wardrobe',
    desc: 'We all need Well Fitted Modular Wardrobes, just like our apparel. Anything out of order would spoil the entire purpose. At the Design Indian Homes, our In-house Brand Design Indian Wardrobe provides us the most perfect fitted Wardrobes, custom wardrobes. We specialise in Exclusive Lacquer Glass Wardrobes, Inline Sliding Wardrobes, Sliding Wardrobes, Hinged Wardrobes, Bespoke Wardrobes and Custom Well Lit Wardrobes, which simply lightens up the room where the closets are fitted. We have mastery in manufacturing custom wardrobes for the past 16 years. Connect without Team Today and Get the Most Affordable Modular Wardrobes across Delhi - NCR - India.',
    items: [],
  },
  {
    id: 6,
    name: 'Exquisite Bathroom',
    slug: 'exquisite-bathroom-remodel-designs',
    noItems: '1012',
    heading: 'Exquisite Bathroom',
    desc: 'That is what is called Luxury, a Well Designed Bathroom brings in Mental Poise and is a great way to unwind after a hard day at work, when you have a nice well lit bathroom with retro lights, well ventilated and professionally planned is all one desires. Even a smaller planned bathroom can be converted using balanced interior planning into a spacious one.    ',
     items: [],
  },
  {
    id: 7,
    name: 'Chilled Out Bar & Party Areas',
    slug: 'chilled-party-bar-unit-designs',
    noItems: '1012',
    heading: 'Chilled Out Bar & Party Areas',
    desc: 'Now coming to the point, for all the social people who indulge in parties at their residences, we have Great News. We design and plan chilled out party and Bar units, connect with us for some cool affordable solutions and check some of our designs. Our team will give you a dedicated party area which will be a great picturesque one.',
    items: [],
  },
  {
    id: 8,
    name: 'Blissful Parents Rooms',
    slug: 'blissful-parents-room-designs-ideas',
    noItems: '1012',
    heading: 'Blissful Parents Rooms ',
    desc: 'We all want to give back to our parents who gave us this very LIFE, so why not give them a great design for their personal space. We take delight in planning parents rooms meticulously, connect with our Team and get the most affordable quotes today. Do Check some of our retro designs for parents bedroom designs. ',
    items: [],
  },
  {
    id: 9,
    name: 'Spellbinding Living Rooms',
    slug: 'spellbinding-living-room-designs',
    noItems: '1012',
    heading: 'Spellbinding Living Rooms',
    desc: 'Get an amazing makeover of your living room by our team Design Indian Homes. We have some of the top notch solutions for redesigning your Living Room at most affordable prices. Connect with us Today and Get a Spellbinding Living Room to socialize with....',
    items: [],
  },
  {
    id: 10,
    name: 'Delicious Kitchens',
    slug: 'delicious-modular-kitchen-designs',
    noItems: '1012',
    heading: 'Delicious Modular Kitchen Designs',
    desc: 'Cooking is better with our Modular Kitchens, this has been proven for more than 2 decades, our brand Design Indian Kitchen is the largest manufacturer of Modular Kitchens across North India. Connect with us and get a beautiful affordable modular kitchen, and Remember - Our Kitchens Taste Good..',
    items: [],
  },
  {
    id: 11,
    name: 'Mesmerising Modern Interiors',
    slug: 'mesmerizing-modern-home-interiors',
    noItems: '1012',
    heading: 'Mesmerising Modern Interiors ',
    desc: 'When you have a Classy Interior in your residence, there are many factors which add on to the space. The first is that you will remain cheerful, the vibrant interiors definitely rejuvenates the mood and creates a harmonious atmosphere, second is you can socialize in the happy place, third is you add on to the value of the existing property. Get in touch with us and get a Mesmerising Modern Interior Today.',
    items: [],
  },
  


]
