export const pagesData = [
  {
    id: 0,
    name: 'Wooden Polishing',
    slug: '/wooden-polishing-designs',
    noItems: '2047',
    heading: 'Wooden Polishing',
    desc: 'Some of the amazing polishing makeovers start with us, now get exclusive polish works with our brand Design Indian Homes. We have dedicated teams for polishing your doors, windows, table chairs and many more as per your requirement at affordable prices. Check out some of our polish design samples today. We have in-house polish types like PU, hammertone, acrylic, polyster, varnish, melamine etc.',
  },
  {
    id: 1,
    name: 'Wooden Flooring',
    slug: '/wooden-flooring-designs',
    noItems: '2874',
    heading: 'Wooden Flooring',
    desc: 'Getting a Flooring makeover has never been so easy and convenient, just book with us and we assure you a new floor to step on. We have a huge range of wooden flooring designs and brands we are distributors of. You can all works done as per your budget and in a very organised and timely manner. You can choose our best designs like teak flooring, laminate flooring, vinyl flooring and carpet flooring. Every flooring has a unique aesthetic and look, it will make you wonder in awe. Get some of the top designs in wooden flooring by our Team.',
    items: [],
  },
  {
    id: 2,
    name: 'Vertical Garden',
    slug: '/vertical-garden-designs',
    noItems: '1816',
    heading: 'Vertical Garden',
    desc: 'Ever seen a handing garden, or a ceiling garden ? Astounded. Now get custom gardens as per imagination with our team. We facilitate and deal in mostly all types of vertical gardens and landscaping. Get a beautiful outdoor or indoor design of a vertical garden by design Indian homes team to find a space for greenery, wherever you want in your residence. Vertical Gardens can be designed on your walls, terrace, fences, rooms, tv units and doors also, you can display by hanging plant baskets on the walls. Check out our top notch vertical garden designs at the most affordable prices.',
    items: [],
  },
  {
    id: 3,
    name: 'UPVC Windows',
    slug: '/upvc-window-designs',
    noItems: '162',
    heading: 'UPVC Windows',
    desc: 'With huge competition going on in the market in the UPVC segment, we bring you some of the most affordable materials and using the top imported brands. Get it touch for a detailed overview and book a site visit with our team for the same. All types of window designs are available with us and much can be custom made as per design requirements. Check out our trending upvc windows design and brands today & book with us.',
    items: [],
  },
  {
    id: 4,
    name: 'Tiling Designs',
    slug: '/tiling-design-ideas',
    noItems: '809',
    heading: 'Tiling Designs',
    desc: 'Tiling might look a masonry’s work, but ever thought of the technical know how it requires, well. ! here’s where most people go wrong. We need to firstly understand the space where work needs to be executed, further proper drawings are made, detailed markings are done and further a professional team is deployed to get the job done and followed by supervision. Get complete works in tiling design for your bathroom, modular kitchen, bedrooms, and living room by design Indian homes at affordable prices. We have a huge range of tiling designs in mostly every colour, finish, brand and shapes. Check out our Latest Floor and Wall tile Designs for your Home Interiors.',
    items: [],
  },
  {
    id: 5,
    name: 'Sofa Designs',
    slug: '/sofa-designs-ideas',
    noItems: '1165',
    heading: 'Sofa Designs',
    desc: 'When you want to plan your living, a perfect sofa ideally comes in your mind. We at the Design Indian Homes, plan your sofa in most meticulous manner and thus making the space lively. We design, plan and manufacture custom sofas for your residences, get in touch today and get a bespoke sofa furniture by our team.',
    items: [],
  },
  {
    id: 6,
    name: 'Kitchen Lightening',
    slug: '/kitchen-lightening-inspiration-ideas-india',
    noItems: '1012',
    heading: 'Kitchen Lightening',
    desc: 'Light up your Modular Kitchen with well planned lightening solution. Kitchen lighting is the first and most lightning impression for the kitchen. We have a huge range of lightning solutions like overhead cabinet light inbuilt, hanging light, skirting light, profile lightning, handleless lightning, drawer lightning solutions and last the ceiling Cove lights which just blends in everything. Get your kitchen lightening designed and planned by our top design team at affordable prices and check out our best trending lightning designs today for your kitchen.',
    items: [],
  },
  {
    id: 7,
    name: 'Plumbings',
    slug: '/home-plumbing-services-india',
    noItems: '1012',
    heading: 'Plumbings',
    desc: 'One of the most important points to home renovation is to get the plumbing done by professionals, we plan your plumbings in a very organised manner to avoid any type of leakages and issues related to seepages. We have sorted some of the most complex plumbing solutions across Apartments, residences and societies. Get in touch today and book a site visit today.',
    items: [],
  },
  {
    id: 8,
    name: 'Glass Partitions',
    slug: '/glass-partition-designs',
    noItems: '1012',
    heading: 'Glass Partitions',
    desc: 'Trending TV unit designs from design indian homes that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, design indian homes helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 9,
    name: 'Ceilings',
    slug: '/ceiling-design-ideas-inspiration-india',
    noItems: '1012',
    heading: 'Ceiling Designs',
    desc: 'They say one may beautify the entire room, but miss out on the right ceiling design. We must understand the ceiling are an integral part of the custom interiors we do, by choosing the right design for the ceiling, we may ruin the entire space. Therefore, at Design Indian Homes, we bring you hundreds of design options for choosing the best fit for your ceiling. Right from Gypsum, POP, Wooden, Teak, Bamboo, Glass, we have mostly all types of ceiling works. Check out some of our Ceiling designs and Book a Visit Today.',
    items: [],
  },
  {
    id: 10,
    name: 'Wall Panelling',
    slug: '/wall-panelling-designs',
    noItems: '1012',
    heading: 'Wall Panelling',
    desc: 'By using the right combinations for wall panelling, we assure you that the space would be beautified beyond previous recognition. A right choice for wall panelling, whether in pure teak, PVC, WPC or POP’s will liven up the interiors and will decorate it to perfection. For all of these, we need a professional wall panelling expert, who would get it to select, design and plan execution for the walls. Check out some of our exclusive wall panelling designs and book a visit today.',
    items: [],
  },

  {
    id: 11,
    name: 'Exterior Cladding',
    slug: '/exterior-cladding-design-ideas',
    noItems: '1012',
    heading: 'Exterior-Cladding',
    desc: 'With over tens and thousands of design options in exterior cladding, mainly comprising of HPL, Custom Tiles, Marble Pieces, Glass fixtures and panelling, we have an effective detailed wall cladding designs for your outdoors to give protective layer when it comes to protecting your interiors and beautify your homes from the exterior. Check out some of our exclusive exterior cladding designs and book a visit today.',
    items: [],
  },
  {
    id: 12,
    name: 'Door',
    slug: '/door-design-dealers-manufacturers-india',
    noItems: '1012',
    heading: 'Door Designs',
    desc: 'We are experts when it comes to custom doors, we have mostly all types of doors for your residence. We are manufacturing veneer doors, laminated doors, teak doors and just any custom type of sliding doors, UPVC, Steel, aluminium or pocket doors can be designed and planned by our team. Check out some of our door designs and book a visit today.',
    items: [],
  },
  {
    id: 13,
    name: 'Electric Works',
    slug: '/home-electric-works-services',
    noItems: '1012',
    heading: 'Electric Works',
    desc: 'Get Professional electric designs by our MEP Team for proper planning and executing and planning your electronic equipments for your interior and outdoor. Here’s where most of people go wrong, by going to their street smart electrician and then starts the mis-managements and troubles. Get professional solutions today.',
    items: [],
  },
  {
    id: 14,
    name: 'Beds',
    slug: '/bed-designs-dealers-manufacturers-india',
    noItems: '1012',
    heading: 'Beds',
    desc: 'A custom made bed is all that we design at the end of the day, or sometimes throughout the day.. ! We manufacture custom made beds of all sizes and designs, just send us your design and take estimates from our team, we will make sure you have long term relation with your private furniture. Connect with us for a bespoke bed solution and we will be happy to help you..',
    items: [],
  },
  {
    id: 15,
    name: 'Paints',
    slug: '/home-painting-services-delhi-ncr',
    noItems: '1012',
    heading: 'Painting Services',
    desc: 'When it comes to choosing paints, how, where, palette selection and combinations, our team will be at your helm in end to end execution and make your walls a masterpiece, just keep your imagination going further and further and we will give you a concerete flamboyant solution for your residence, office or any type of property across Delhi – NCR. Connect with us and Book a Visit today.',
    items: [],
  },
  {
    id: 16,
    name: 'End to End Interiors',
    slug: '/end-to-end-interior-services-delhi-ncr-india',
    noItems: '1012',
    heading: 'End to End Interiors',
    desc: 'We are masters when it comes to getting complete End to End interiors done, across Delhi – NCR. With over 2700+ projects successfully delivered, we are running top of our game with most affordable end to end interiors in the Town. We take pride in exclaiming that you get us any quote across Delhi – NCR and we assure you a Flat 7% off your interior design with end to end deliveries. Check out our Latest Designs for your Interiors today & book a visit.',
    items: [],
  },

  {
    id: 17,
    name: 'Commercial Interiors',
    slug: '/commercial-interiors-services-delhi-ncr-india',
    noItems: '1012',
    heading: 'Commercial Interiors',
    desc: 'Some of the best commercial offices, showrooms, retailers have been designed by team design indian homes. We you’re your interiors in a very budget friendly and professional manner. Now get complete designs for your interiors in spaces like restaurants, lobbies, offices and retail shops with the beautiful custom renovation services for commercial interior design at affordable budget. Check out some of our Commercial Interior Designs Today.',
    items: [],
  },
  {
    id: 18,
    name: 'Wooden Ceiling',
    slug: '/wooden-ceiling-designs-ideas-inspiration',
    noItems: '1012',
    heading: 'Wooden Ceiling',
    desc: 'With Over 80+ designs to choose from, our team has top custom designs for wooden ceilings. We have some of the coolest and trendiest designs for wooden ceilings. Whether you need it for your commercial space or for your studios or for residential works, we have some of the finest custom designs to suit your requirements. Connect with us Today & Get most affordable solution for your residence.',
    items: [],
  },
]
