export const pagesData = [
  {
    id: 0,
    name: '2 Door Sliding',
    slug: '2-door-sliding-wardrobe-designs',
    noItems: '2047',
    heading: '2 Door Sliding',
    desc: 'A Very Practical and Common sliding solution, which is used by masses. We bring creativity into this and bring you bespoke, custom made 2 door sliding wardrobes across New Delhi - NCR. All Our Wardrobes are made to fit, looks good and are very well planned by our specialists. Get in Touch with us Today.',
    items: [],
  },
  {
    id: 1,
    name: '3 Door Sliding',
    slug: '3-door-sliding-wardrobe-designs',
    noItems: '2874',
    heading: '3 Door Sliding',
    desc: ' Get Beautiful designed Chest of Drawers by our design team to spice up your living areas or Bedrooms. Some of the classic chest of drawers are manufactured by our Brand, book a visit by our Team Today. Take Delight in our products, All Our Chest of Drawers are pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Chest of Drawers.',
    items: [],
  },
  {
    id: 2,
    name: 'Acrylic Wardrobe',
    slug: 'acrylic-wardrobe-designs',
    noItems: '1816',
    heading: 'Acrylic Wardrobe',
    desc: 'One of Our Coolest segment of wardrobes is using the acrylic materials, we have different categories in acrylics and can give custom designs to your wardrobe shutters. We are the largest acrylic wardrobe manufacturers across New Delhi - NCR. We have acrylics from around the work, Spain, Italy, Japan, Austria, German, China, Russia, etc. These are all varying in quality and thickness. Some of these shutters are hand crafted if designs are to be managed in the shutters. Rest, for more .. Do Connect with us Today.',
    items: [],
  },
  {
    id: 3,
    name: 'Hinged Wardrobe',
    slug: 'hinged-wardrobe-designs',
    noItems: '162',
    heading: 'Hinged Wardrobe',
    desc: 'A Common wardrobe, done the uncommon way. All Our Wardrobes are made using some of the finest materials available with exclusive warranties. We are the largest wardrobe manufacturing brand across New Delhi - NCR, we have served more than 9000+ customers across Delhi for Hinged wardrobes. We have wardrobes using some of the top finishes like nano laminates, britlite laminates, charcoal laminates and pure teak. Connect with us to know more.',
    items: [],
  },
  {
    id: 4,
    name: 'Lacqured Wardrobe',
    slug: 'lacquer-glass-wardrobe-designs',
    noItems: '809',
    heading: 'Lacqured Wardrobe',
    desc: 'These wardrobes are a Masterpiece and look like an art piece in the residence, we have the largest collection of lacquer glass wardrobe designs in New Delhi - NCR. Lacquer Glass wardrobe are the most premium materials available in the markets, we are using slim Austrian and Spanish profiles. With more than 200+ lacquer glass wardrobes delivered in a month, Check us our and connect with us Today.',
    items: [],
  },
  {
    id: 5,
    name: 'Laminated Wardrobe',
    slug: 'laminated-wardrobe-designs',
    noItems: '1165',
    heading: 'Laminated Wardrobe',
    desc: 'We have more than 2000+ of different types of wardrobes laminates available in our collection. Visit our Boutique office and check the complete collection of our materials. These are the most affordable types of wardrobes and are used mostly in all types of residences. Connect with us for the most affordable wardrobe solution.',
    items: [],
  },
  {
    id: 6,
    name: 'Membrane Wardrobe',
    slug: 'membrane-wardrobe-designs',
    noItems: '1012',
    heading: 'Memebrane Wardrobe',
    desc: 'Wardrobes in Membrane shutters are the next Inn thing of the Premium Collection. These are made of German sheets which are pressed over the designer wood shutters, and then meticulously moulded in the design, We have the complete collection, and have more than 160+ dealers across New Delhi - NCR for our premium membrane shutters. Connect with us today and get a Cool Membrane Wardrobe today.',
    items: [],
  },
  {
    id: 7,
    name: 'Polished Wardrobe',
    slug: 'polished-wardrobe-designs',
    noItems: '2047',
    heading: 'Polished Wardrobe',
    desc: 'We Do PU Polished wardrobes, but with a catch - we do it in thick shutters, we do polyester or acrylics, PU or hammertone to give an ultimate cool finish, we do it in the best possible practise and we do it really nicely. All our PU polished shutters are made of High End PU polish and add a charm to your residence. Connect with us Today & Get the Best out of your Bedroom.',
  },
  {
    id: 8,
    name: 'Teak Wardrobe',
    slug: 'teak-wardrobe-designs',
    noItems: '2874',
    heading: 'Teak Wardrobe',
    desc: 'Our Teak Wardrobes are made out of hardcore seasoned wood which are never bending, long lasting and top class. These shutters are super premium as there are long processes involved in these. They are luxurious, class as well as contemporary and really give a rich look to the overall interiors. Connect with us Today & Get the Best out of your Bedroom.',
    items: [],
  },
  {
    id: 9,
    name: 'Veener Wardrobe',
    slug: 'veener-wardrobe-designs',
    noItems: '1816',
    heading: 'Veener Wardrobe',
    desc: 'These are called Old is Gold, these veneer wardrobes are looking good since ages. We are using some of the finest original, non-reconstructed veneers available in the markets, all our veneered wardrobes are made timelessly classic and super smooth using silk acrylic PU. Connect with us Today & Get the Best out of your Bedroom.',
    items: [],
  },
  {
    id: 10,
    name: 'Walk in wardrobe',
    slug: 'walk-in-wardrobe-designs',
    noItems: '162',
    heading: 'Walk in wardrobe',
    desc: 'That Sounds BIG, these wardrobe are super cool, super nicely planned and super spacious, they bring out the best of any residence. Very few have such spaces, and those who have, must get it planned very very nicely. Well, we are here to serve you, we have delivered more than 250+ premium walk in wardrobes and are continuing the great work. Connect with us Today and Become a part of our FAMILY.',
    items: [],
  },
  {
    id: 11,
    name: 'Cane wardrobe',
    slug: 'cane-wardrobe-designs-dealers-manufacturers-in-delhi-gurgaon-noida-india',
    noItems: '162',
    heading: 'Cane Wardrobe',
    desc: 'At the Design Indian Homes Brand, we have myriad designs for cane wardrobes. We custom design and manufacture as per the choice and all our cane wardrobe designs are unique, bespoke and handcrafted. We are the largest dealers and manufacturers for Modular Wardrobes, Designer Wardrobes, Custom Fit Wardrobes and All Types of Sliding Closets. We have the largest collection of wardrobes and are serving across New Delhi - NCR - India. Connect with us Today and get the top notch quality at the most lowest price.',
    items: [],
  },
  {
    id: 12,
    name: 'CNC Wardrobe Designs',
    slug: 'cnc-designer-wardrobe-designs-dealers-manufacturers-in-delhi-gurgaon-noida-india',
    noItems: '162',
    heading: 'CNC Wardrobe Designs',
    desc: 'With over 90+ types of CNC Designs, or cut out wardrobe designs, We are the largest dealers and manufacturers for Modular Wardrobes, Designer Wardrobes, Custom Fit Wardrobes and All Types of Sliding Closets. We have the largest collection of wardrobes and are serving across New Delhi - NCR - India. Connect with us Today and get the top notch quality at the most lowest price. We are manufacturing CNC wardrobe at the lowest price and more than 950+ architects, interior designers and builders are associated with our Brand. Come Directly and save the middleman cost.',
    items: [],
  },
  {
    id: 13,
    name: 'Leatherette Wardrobe Designs',
    slug: 'leatherite-designer-wardrobe-designs-dealers-manufacturers-in-delhi-gurgaon-noida-india',
    noItems: '162',
    heading: 'Leatherette Wardrobe Designs ',
    desc: 'With over 90+ types of Leatherette Wardrobe Designs, or premium Leather Shuttered Wardrobe designs, We are the largest dealers and manufacturers for Modular Wardrobes, Designer Wardrobes, Custom Fit Wardrobes and All Types of Sliding Closets. We have the top exclusive collection of wardrobes and are serving across New Delhi - NCR - India. Connect with us Today and get the top notch quality at the most lowest price. We are manufacturing Leatherette Wardrobe at the lowest price and more than 950+ Architects, Interior Designers and Builders are associated with our Brand. Come Directly and save the middleman cost.',
    items: [],
  },
]
