export default function sitemap() {
  return [
    {
      url: 'https://www.designindianhomes.com/',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 1.0,
    },
    {
      url: 'https://www.designindianhomes.com/book-with-top-interior-designers-architects',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/refer-and-get-rewards-interior-designers',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/collaborate-with-architects-interior-designers',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/modular-interior-design-ideas',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/home-interior-services-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/architectural-designs-services-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/modular-kitchen-top-brand-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/wardrobe-design-gallery-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/modular-interiors',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/home-interior-designs-designing-estimates-pricing',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/book-a-interior-design-visit',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/homes-by-design-indian-homes',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/get-free-estimate-by-top-interior-brand-in-delhi-gurgaon-noida-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/bathroom-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/bedroom-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/bed-designs-dealers-manufacturers-india-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/wood-door-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/home-electric-works-services-interiors',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/exterior-cladding-design-ideas-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/glass-partition-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/kitchen-lightening-inspiration-ideas-india-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/modular-kitchen-top-brand-india/kitchen-renovations',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/plumbing-works-interiors',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/ceiling-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/sofa-designs-ideas',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/tiling-design-ideas',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/upvc-window-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/vertical-garden-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/wall-panelling-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/wooden-flooring-designs-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/offers',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/banquet-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/farmhouse-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/gym-spa-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/hotel-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/home-interior-designs-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/living-room-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/lounge-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/mandir-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/structural-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/terrace-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/villa-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/luxury-interior-designers-architect-services-in-delhi-gurgaon-noida-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/luxury-residence-designs-delhi-india/luxury-interior',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/selected-homes-exclusive-interior-designs-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/foyer-area-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/book-visit',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/schedule-videocall',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/types-of-modular-kitchens',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/modular-kitchen-top-brand-india/modular-kitchen-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/luxury-residence-designs-delhi-india/luxury-structural',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/about-best-interior-designers-architects',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/home-renovation-services',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/virtual-interior-designing-meeting',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/customer-reviews-interior-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/home-interior-designs-designing-plans-for-residences',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/why-choose-the-best-interior-designers',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/join-the-largest-interior-designing-brand',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/join-us',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/privacy',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.designindianhomes.com/home-interior-designs',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.64,
    },
    {
      url: 'https://www.designindianhomes.com/home-renovation-service',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.64,
    },
    {
      url: 'https://www.designindianhomes.com/shutter-finish',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.64,
    },
    {
      url: 'https://www.designindianhomes.com/types-of-wardrobe',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.64,
    },
    {
      url: 'https://www.designindianhomes.com/interior-digest-magazine-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.64,
    },
    {
      url: 'https://www.designindianhomes.com/design-ideas',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.64,
    },
    {
      url: 'https://www.designindianhomes.com/luxury-residence-designs-delhi-india',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.64,
    },
  ]
}
