export const pagesData = [
  {
    id: 0,
    name: 'Structural Renovation',
    slug: '/structural-renovation',
    noItems: '2',
    heading: 'Structural Renovation',
    desc: 'Get your residence structure renovated by The Design Indian Homes brand. We have the best architects, structural engineers, civil engineers and interior designers team from designing an end to end solution for a new & elegant upgrading of your House. Check out our latest structure design for your next renovation work.',
    items: [],
  },
  {
    id: 1,
    name: 'Interior Renovation',
    slug: '/interior-renovation',
    noItems: '4',
    heading: 'Interior Renovation',
    desc: ' Some of the Most Affordable Interior renovations from the scrap to a beautiful outcome with end to end designs & executions. We have the top design team and end to end executing teams for the top notch interior design for your residence. Browse our latest collection for your interior designs, get ideas, & Be Inspired.',
    items: [],
  },
  {
    id: 2,
    name: 'Bedroom Renovation',
    slug: '/bedroom-renovation',
    noItems: '5',
    heading: 'Bedroom Renovation',
    desc: 'A Makeover for the bedroom is always wanted. Now Get bedroom redesigned from your existing to a new bedroom Interior at most unbelievable prices across Delhi - NCR. Go check out our latest bedroom interior designs and connect with us Today.',
    items: [],
  },
  {
    id: 3,
    name: 'Lounge Renovation',
    slug: '/lounge-renovation',
    noItems: '6',
    heading: 'Lounge Renovation',
    desc: 'Get your lounge renovated from the outdated to trending designs. By Design Indian homes. Check out our latest trending design for your lounge areas as per your convenience.',
    items: [],
  },
  {
    id: 4,
    name: 'Bathroom Renovation',
    slug: '/bathroom-renovation',
    noItems: '7',
    heading: 'Bathroom Renovation',
    desc: 'Get your bathroom renovated to trending design by Design Indian Homes. We have a wide range of tiling, bath ware accessories and many vanity design options for your Bathroom. Browse our pages for your elegant Bathroom Design.',
    items: [],
  },
  {
    id: 5,
    name: 'Terrace Renovation',
    slug: '/terrace-renovation',
    noItems: '6',
    heading: 'Terrace Renovation',
    desc: 'Now all done, we need to get our Terrace Revamped.. ? You are at the right place, now renovate your terrace area to make it look elegant and awesome with the Design Indian Homes Team. We have some top quality materials & assorted Material specifications for your terrace to beautify. Also to cover small roof spaces, we design and do complete landscaping also. Check out our latest designs today.',
    items: [],
  },
  {
    id: 6,
    name: 'Living Room Renovation',
    slug: '/living-room-renovation',
    noItems: '57',
    heading: 'Living Room Renovation',
    desc: 'Design Indian homes gives a wide range of exquisite designs to renovate your new homes with bespoke living room designs to select from, we have a dedicated range of tv units, wall paintings, wallpaper and paneling for your living room. With different decorations and ideas, you will love to socialize.',
    items: [],
  },
  {
    id: 7,
    name: 'Modular Kitchen Renovation',
    slug: '/modular-kitchen-renovation',
    noItems: '87',
    heading: 'Modular Kitchen Renovation',
    desc: 'Get Your Kitchen renovated By Design Indian Homes Brand at the most affordable prices, bring us any quote and we assure you flat 7% off on any. Book us Direct and save a minimum 30% of the Middleman cost. With a wide range of Modular kitchen design Option at our unit, custom fit in any shape as per your space. Also we have some of the top material specifications, hardwares, countertops, and lighting options for your new kitchen design. Check out our Collection of Modular Kitchen Designs.',
    items: [],
  },
  {
    id: 8,
    name: 'Wardrobe Renovation',
    slug: '/wardrobe-renovation',
    noItems: '564',
    heading: 'Wardrobe Renovation',
    desc: ' A Wardrobe should be Good Looking, for you to look good. Now Get your Wardrobe Renovated from an obsolete design to a trendy flamboyant design, yet very affordable with proper storage planning by Our Brand Design Indian Homes. With the proper material specification and Fittings, we assure you a Masterpiece. Check out some of our delivered designs & Book with us today for Thousands of more options for renovating your Wardrobe.',
    items: [],
  },
  {
    id: 9,
    name: 'Mandir Renovation',
    slug: '/mandir-renovation',
    noItems: '345',
    heading: 'Mandir Renovation',
    desc: 'We take delight in designing and planning a Mandir Space, it iis close to our Heart, where Almighty Resides. Now Get your mandir renovated by Our Team at Design Indian Homes, and get an affordable solution which lasts long and you can Pray in Peace. We will give some concepts once you book with us with detailed material specification and fit to room options & proper designs by our design team. Check out some of our Soulful Mandir Designs.',
    items: [],
  },
  {
    id: 10,
    name: 'GYM & Spas Renovation',
    slug: '/gym-spas-renovation',
    noItems: '768',
    heading: 'GYM & Spas Renovation',
    desc: ' Gyms should be looking energetic and not dull, fatigued. Now Upgrade your Gym design and spas designs and renovate with Team Design Indian Homes with Proper designing, planning & execution. Now make the spaces look elegant and vibrant with the help of our experienced team. Browse our designs for inspiration and connect with us for an Upgradation renovation for your GYM and SPA.',
    items: [],
  },
  {
    id: 11,
    name: 'Hotel Renovation',
    slug: '/hotel-renovation',
    noItems: '345',
    heading: 'Hotel Renovation',
    desc: 'We are experts in commercial renovations, these are segregated in 2 segments, a) Modular Interiors and 2) Civil Executions. With our team you will not be entangled in any hassle, now get your Hotel renovated in a timely and organized manner. And Attract your Guest with new Trendy room designs & complete overall décor upgrade. Get proper design, advice and execution by our design team Today.',
    items: [],
  },
  {
    id: 12,
    name: 'Farmhouse Renovation',
    slug: '/farmhouse-renovation',
    noItems: '345',
    heading: 'Farmhouse Renovation',
    desc: 'That what a Farm Looks, that’s what your family and relatives will exclaim once the farm is renovated by our Team. Now renovate your FarmHouse into a contemporary design by the Design Indian Homes Team, through proper planning, design with material specification & meticulous execution. Check out some of our designs for farm houses. Book With us Today for an Affordable Makeover.',
    items: [],
  },
  {
    id: 13,
    name: 'Banquet Renovation',
    slug: '/banquet-renovation',
    noItems: '453',
    heading: 'Banquet Renovation',
    desc: 'A Shining Makeover for your Banquet, Get your banquet renovated to a upgraded modern design with shimmer to attract your guests and make them delighted with a memorable makeover, Let your clients book in a huge ceremonies after a Total makeover, that also affordable and delivered on time. We have some of the top notch designers, architects and civil team to modernize your banquet hall as per your requirement.',
    items: [],
  },
  {
    id: 14,
    name: 'Villa Renovation',
    slug: '/villa-renovation',
    noItems: '6576',
    heading: 'Villa Renovation',
    desc: 'Get your Villa Renovated by our Team with proper planning and designing, we have a dedicated PMC team to manage your area. Also we have a dedicated team of different project managers for your end to end villa renovation solution in Delhi – Gurgaon – Noida – Faridabad - India. For both interior and exteriors along with structures. Check out our latest design for your villas & Get back to us for a Site Visit followed by estimates.',
    items: [],
  },
]
