export const pagesData = [
  {
    id: 0,
    name: '1BHK residence interior designs',
    slug: '1bhk-residence-interior-designs',
    noItems: '2047',
    heading: '1BHK residence interior designs',
    desc: ' When you have a budget, why not get it Big on Deliveries. Get custom interiors for your 1 Bhk residence ? With proper planning and designing by Design Indian Homes. We have a wide range of material specifications. Check out our Design Collection for your 1bhk residence. We have some of the top Exclusive solutions for your 1BKH residence across New Delhi – NCR, we create custom interior design for your space, connect with our Team for experiencing some of the most creative interior makeovers.',
    items: [],
  },
  {
    id: 1,
    name: '2BHK residence interior designs',
    slug: '2bhk-residence-interior-designs',
    noItems: '2874',
    heading: '2BHK residence interior designs',
    desc: 'When Luxury can be affordable, why not choose the best for your interior makeovers. Check out our Design Collection for your 2bhk residences. We have some of the top Exclusive solutions for your 2BKH residence across New Delhi – NCR, we create custom interior design for your space, connect with our Team for experiencing some of the most creative interior makeovers.',
    items: [],
  },
  {
    id: 2,
    name: '3BHK Residence interior designs',
    slug: '3bhk-residence-interior-designs',
    noItems: '1816',
    heading: '3BHK Residence interior designs',
    desc: 'Can you Tell who did this awesome makeover.. ? A common question asked by our clients extended family & friends. Check out our Design Collection for your 3bhk residence. We have some of the top Exclusive solutions for your 3BKH residence across New Delhi – NCR, we create custom interior design for your space, connect with our Team for experiencing some of the most creative interior makeovers.',
    items: [],
  },
  {
    id: 3,
    name: '4BHK Residence interior designs',
    slug: '4bhk-residence-interior-designs',
    noItems: '162',
    heading: '4BHK Residence interior designs',
    desc: ' A Dedicated Bespoke Solution for your space, we have some of the top Exclusive solutions for your 4BKH residence across New Delhi – NCR, we create custom interior design for your space, connect with our Team for experiencing some of the most creative interior makeovers..',
    items: [],
  },
  {
    id: 4,
    name: 'Villa interior designs',
    slug: 'villa',
    noItems: '809',
    heading: 'Villa interior designs',
    desc: 'As Classy as it can get, now plan and redesign your villas by our Professional team at Design Indian Homes. Now Get your villa designed with proper aesthetic designs, structure planning and detailed execution. We plan and Design your villa as per your bespoke needs. We have a massive range of fixtures for decors and design for your interior needs. Connect with us for Any type of Design Solutions.',
    items: [],
  },
  {
    id: 5,
    name: 'Farmhouse interior designs',
    slug: 'farmhouse-interior-designs',
    noItems: '1165',
    heading: 'Farmhouse interior designs',
    desc: 'What is the fun having a farm, undone & Dilapidated … ? Get Artistic Makeovers and get it completely redesigned with the most affordable solutions. Connect with our Team for End to End interior solutions today, we are serving across Delhi – NCR – India.',
    items: [],
  },
  {
    id: 6,
    name: 'Penthouse interior designs',
    slug: 'penthouse-interior-designs',
    noItems: '1012',
    heading: 'Penthouse interior designs',
    desc: 'Wow Now that’s what is expected from a Pent-House, why do we call indulgence a sin when it is so affordable. Get a complete makeover of your penthouse at the most affordable prices across New Delhi – NCR -India. Connect with our Team Today.',
    items: [],
  },
  {
    id: 7,
    name: 'studio apartment interior designs',
    slug: 'studio-apartment-interior-designs',
    noItems: '1012',
    heading: 'Studio apartment interior designs',
    desc: 'A Studio that stands out, affordable luxury at its best. Now Get your Studio Interior Designed with detailed planning and designing with complete essentials to create complementing palette colors for your Interior Living Space. Check out our Exclusive Studio Designs for your residences across Delhi - NCR.',
    items: [],
  },
  {
    id: 8,
    name: 'Bunglow interior designs',
    slug: 'bunglow-interior-designs',
    noItems: '1012',
    heading: 'Bunglow interior designs',
    desc: 'Get the Most out of your Spaces, We Design, Plan and Execute in the most organized skilled manner, our Team took a complete turnkey solution for your bungalow. We Aspire to create a minimalistic and royal theme for your interiors with more space for custom innovative design than the usual routed design. Check and Browse our Collection of Bungalow Interior Design, we are serving across Delhi - NCR.',
    items: [],
  },
  {
    id: 9,
    name: 'Duplex Residence interior designs',
    slug: 'duplex-residence-interior-designs',
    noItems: '1012',
    heading: 'Duplex Residence interior designs',
    desc: 'Top Class Design Execution of a Duplex, that is what all your friends and relatives will exclaim. Now Get your duplex designed with over 80+ design themes or it can be any theme you can imagine. With the overall space for your interior like kitchen, living rooms, bedroom and bathroom planned as per custom design, we assure you a top class duplex interior design and execution across New Delhi - NCR. Connect with us Today and Book a Visit.',
    items: [],
  },
  {
    id: 10,
    name: 'Cottage interior designs',
    slug: 'cottage-interior-designs',
    noItems: '1012',
    heading: 'Cottage interior designs',
    desc: 'A Cottage should be Warm, cozy and lovable. That is how we design your cottage. Get Top interior design for your cottage to look vintage, rustic yet full of charm with our designs. With decorating it in natural tones and playing with pastels, we will ensure you hit the nail across your Guests and Homestay Guests. And also with the shaker style, traditional, classic kitchen design for your cottage, will give an antique aesthetic look. Choose a Cool & Mesmerizing design for your cottage interior today. Book with us for the most affordable solution.',
    items: [],
  },
  {
    id: 11,
    name: 'Residential Office Designs',
    slug: 'residential-Offices-designs',
    noItems: '1012',
    heading: 'Residential office designs',
    desc: 'Elevate your home office experience with our exclusive residential office interior designs. At Design Indian Homes, we believe that your workspace should be an extension of your personality and work style. Our team of skilled designers is dedicated to creating a harmonious balance between functionality and aesthetics, ensuring that your home office is a reflection of your unique taste.',
    items: [],
  },


]
