export const pagesData = [
  {
    id: 0,
    name: 'Custom Modular Kitchen',
    slug: 'custom-modular-kitchen',
    noItems: '2047',
    heading: 'Custom Modular Kitchen',
    desc: 'We take keen interest in delivering graceful Mandirs. We have a huge range of mandir designs for your interiors. Check out our Mandir section for a huge range of Temple designs & get a Temple today at an affordable price which can be customized as per your design. Delight yourself in our products, All Our Mandir Units are very pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off.',
    items: [],
  },
  {
    id: 1,
    name: 'G Shape modular kitchen',
    slug: 'g-shape-modular-kitchen',
    noItems: '2874',
    heading: 'G Shape Modular Kitchenn',
    desc: ' Get Beautiful designed Chest of Drawers by our design team to spice up your living areas or Bedrooms. Some of the classic chest of drawers are manufactured by our Brand, book a visit by our Team Today. Take Delight in our products, All Our Chest of Drawers are pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Chest of Drawers.',
    items: [],
  },
  {
    id: 2,
    name: 'Garden Modular Kitchen',
    slug: 'garden-modular-kitchen',
    noItems: '1816',
    heading: 'Garden Modular Kitchen',
    desc: ' We have some exquisite designs for Bar Units, we can provide you some of the most creative bar designs to liven up your parties. We design bespoke bar units with different types of storage making it aesthetic for wine bottles, glass cups and for built-in chillers if required. Take Delight in our products, All Our Bar Units are pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since the past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, teak, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Bar Units.',
    items: [],
  },
  {
    id: 3,
    name: 'Island modular Kitchen',
    slug: 'island-modular-kitchen',
    noItems: '162',
    heading: 'Island Modular Kitchen',
    desc: 'An Amazing Makeover for Your Bed Side Tables, Now get a customized designed side table by design Indian homes at most affordable prices. We have a huge range of drawers fitting and designers shutter options for your side tables. Check out our latest design today. Take Delight in our products, All Our Side Tables are pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, teak, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Side Tables.',
    items: [],
  },
  {
    id: 4,
    name: 'L Shape Modular Kitchen',
    slug: 'l-shape-modular-kitchen',
    noItems: '809',
    heading: 'L shape Modular kitchen',
    desc: 'Now that is a Masterpiece and a Space Saver, Get a design by our team for your customized foldable bed with storage for space saving in your bedroom with different finishes. Check out our topmost foldable beds design. Take Delight in our products, All Our Foldable Bed Designs are pocket friendly and delivered on timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, teak, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Foldable Beds.',
    items: [],
  },
  {
    id: 5,
    name: 'Open Modular Kitchen',
    slug: 'open-modular-kitchen',
    noItems: '1165',
    heading: 'Open Modular Kitchen',
    desc: 'A Grand Entry for your Entrances, Now Get a designer foyer area with a beautiful chest of drawers and assorted wall panelling and lightning solutions as per custom design. Check out our beautiful foyer area designs for your interiors. Take Delight in our products, All Our Foyer Area Designs are pocket friendly and delivered on timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, teak, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Foyer Area.',
    items: [],
  },
  {
    id: 6,
    name: 'Parllel Modular Kitchen',
    slug: 'parllel-modular-kitchen',
    noItems: '1012',
    heading: 'Parllel Modular Kitchen',
    desc: 'Trending TV unit designs from Design Indian Homes that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Design Indian Homes helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 7,
    name: 'Peninsula Modular Kitchen',
    slug: 'peninsula-modular-kitchen',
    noItems: '2047',
    heading: 'Peninsula Modular Kitchen',
    desc: ' Get a Top Quality, functional, Affordable & Well Lit Modular Kitchen, using the Top Notch fittings. We Design from a basic simple modular kitchen to an exclusive luxury modular kitchen which perfects for convenience and aesthetics. All Our Modular Kitchens are budget friendly, and we assure you 100% guaranteed quotes across Delhi NCR, we have claimed for the past 9 years, that you bring us any Quote and we offer you Flat 7% off. We design your Modular Kitchen exactly as per bespoke requirements, in all shapes like L shape, G, U shape, Island kitchen, Open kitchen etc with distinctive types of finishes in acrylic, membrane, designer laminates, lacquer glass and veneer shutter. Check out some of the coolest kitchen designs we have with us.',
  },
  {
    id: 8,
    name: 'Straight Modular Kitchen',
    slug: 'straight-modular-kitchen',
    noItems: '2874',
    heading: 'Straight Modular Kitchen',
    desc: 'We at Design Indian Homes design & manufacture beautiful affordable vanities which have dedicated functions like custom drawers, internal storages and with elegant handles. All Our Bathroom Vanities are economical and delivered on a very timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off.',
    items: [],
  },
  {
    id: 9,
    name: 'Studio Modular Kitchen',
    slug: 'studio-modular-kitchen',
    noItems: '1816',
    heading: 'Studio Modular Kitchen',
    desc: 'Now get a Bespoke Crockery Unit with our team, we have a myriad range of Crockery Unit designs with glass, acrylics and premium Fenix materials. All Our Crockery Units are very pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we have claimed since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like premium laminates, Stone Veneers, Glass Acrylics and lacquer glass. Check out our designs for some of the top ideas for your Crockery Units.',
    items: [],
  },
  {
    id: 10,
    name: 'Terrace Modular Kitchen',
    slug: 'terrace-modular-kitchen',
    noItems: '162',
    heading: 'Terrace Modular Kitchen',
    desc: 'When you really deserve a perfect partition, you must get one. Now get Beautiful Glass Partitions for your interiors to deck up your spaces. Delight yourself in our products, All Our Glass Partitions are very pocket friendly and delivered on a timely basis, we assure you 100% guaranteed quotes across Delhi NCR, we stake claim since past 9 years, that you bring us any Quote and we offer you Flat 7% off. We provide different finishes of the shutters like slim profiled, zed profiled, cube profile and lacquered. Check out our designs for some of the top ideas for your Glass Partitions.',
    items: [],
  },
  {
    id: 11,
    name: 'U Shape Modular Kitchen',
    slug: 'u-shape-modular-kitchen',
    noItems: '162',
    heading: 'U shape Modukar Kitchen',
    desc: 'At the Design Indian Homes Brand, we have myriad designs for cane wardrobes. We custom design and manufacture as per the choice and all our cane wardrobe designs are unique, bespoke and handcrafted. We are the largest dealers and manufacturers for Modular Wardrobes, Designer Wardrobes, Custom Fit Wardrobes and All Types of Sliding Closets. We have the largest collection of wardrobes and are serving across New Delhi - NCR - India. Connect with us Today and get the top notch quality at the most lowest price.',
    items: [],
  },
 
]
